### ISSUE TITLE
点击 logo 图像无法跳转至首页

### ISSUE THREAD

**Issue by Shitao5** [yihui/hugo-paged#1]
Hello yihui! 

hugo-paged 主题很酷，俺在尝试配置。

过程中发现在添加 logo 图像后点击 logo 跳回网页首页的功能就失效了。我试了几次后，总结问题如下：

1. 不添加 logo 图像，如[主题示例网站](https://paged.yihui.org/)：点击 logo text 即可跳转，没有问题。
2. 添加 logo 图像后，如[yihui 的博客](https://yihui.org/cn/)和我本地的博客：
   1. 如果鼠标移动到 logo 上时 logo 隐藏（鼠标指针变成小手），点击无法跳转；
   2. 如果鼠标移动到 logo 上时 logo 没有隐藏（还是指针型），点击可以跳转。

我尝试修改了 `.logo img { display: none;}` 等等，但都没有命中要害，还是来留个 issue 吧🥲

我使用的是：

- 浏览器：Chrome Version 117.0.5938.92 (Official Build) (64-bit)
- blogdown：1.18
- Hugo：0.113.0

**Comment by yihui** [comment]
很好，你活捉了一只大虫。已修正。谢谢！
