### ISSUE TITLE
使用rmarkdown渲染直接报错

### ISSUE THREAD

**Issue by swcyo** [yihui/hugo-paged#2]
国内的网，提不成。。。

**Comment by yihui** [comment]
啥错？

**Comment by swcyo** [comment]
> 啥错？

``` {r}
 blogdown:::serve_site()
```
> Launching the server via the command:
  /Users/mac/Library/Application Support/Hugo/0.106.0/hugo server --bind 127.0.0.1 -p 4321 --themesDir themes --theme hugo-paged -D -F --navigateToChanged
Error: Error building site: failed to render pages: render of "page" failed: "/Users/mac/Documents/GitHub/page/themes/hugo-paged/layouts/_default/single.html:1:3": execute of template failed: template: _default/single.html:1:3: executing "_default/single.html" at <partial "header.html" .>: error calling partial: "/Users/mac/Documents/GitHub/page/themes/hugo-paged/layouts/partials/header.html:56:42": execute of template failed: template: partials/header.html:56:42: executing "partials/header.html" at <index .Site.Params.logo $section>: error calling index: index of untyped nil

**Comment by yihui** [comment]
Hugo 版本太低。要么 `blogdown::install_hugo()` 升级，要么把你的 `hugo.yaml` 重命名为 `config.yaml`。
