### ISSUE TITLE
Emoji's color gets inverted in the dark mode

### ISSUE THREAD

**Issue by CyrusYip** [yihui/hugo-paged#7]
## Reproduction

```shell
git clone https://github.com/yihui/hugo-paged.git
cd hugo-paged
git reset --hard cc8e306
echo '🙈' > exampleSite/content/_index.md # see-no-evil \u{1F648}
hugo server --source exampleSite --themesDir ../..
```

Dark mode (ugly):

![Screenshot_20240724_174400](https://github.com/user-attachments/assets/97c5752d-d3b2-4d08-9b90-571b26304553)

Light mode (normal):

![Screenshot_20240724_174516](https://github.com/user-attachments/assets/1cd7bdbb-ebdb-496a-a45b-b6a0c4b5482b)

**Comment by yihui** [comment]
Emojis can't be selected via CSS selectors, so I'm afraid I can't do anything about them.

**Comment by CyrusYip** [comment]
`filter: invert(1)` is hacky. If you are content with current colors in the dark mode, maybe you can use color picker software to get color values and put them in `@media (prefers-color-scheme: dark) { }`.

**Comment by yihui** [comment]
It is a hack indeed. And yes, I can get the color values for the dark mode, but I don't have time or interest...

**Comment by CyrusYip** [comment]
> I can get the color values for the dark mode, but I don't have time or interest...

Me neither. I'll let you decide whether to close this issue.
